### ISSUE TITLE
官网首页导航栏重构

### ISSUE THREAD

**Issue by zhuangbiaowei** [kaiyuanshe/kaiyuanshe.github.io#117]
从左自右，应该如下展示：

1. 组织架构
    1. 组织机构全景图
    2. 理事会
    3. 执行委员会
    4. 项目委员会
    5. 顾问委员会
    6. 法律咨询委员会
    7. 正式成员
2. 开源文库
    1. 中国开源年会（COSCon）
    2. 开源社城市社区（KCC）
    3. 开源读书会
    4. 原创文章
    5. 翻译文章
    6. 全部文章
3. 年度报告
    1. 中国开源年度报告
    2. 开源社年度报告
4. 精彩活动
5. 合作伙伴
6. 开源百宝箱
7. 关于我们（请打开一个新的Tab显示）

**Comment by tianheg** [comment]
> 我建议将开源社的愿景：“立足中国、贡献全球，推动开源成为新时代的生活方式” 放在官网里置顶。顺序应该是：我们的愿景，我们的使命，我们的原则，最后才是我们的项目，如此也能与开源社的新章程呼应。
> ——@tedliu1
