### ISSUE TITLE
活动财务公开表格页

### ISSUE THREAD

**Issue by TechQuery** [kaiyuanshe/kaiyuanshe.github.io#130]
## 界面参考

1. https://web-conf.dev/#2019/accounts/
2. https://next-bootstrap-ts.vercel.app/pagination

## 数据结构

https://kaiyuanshe.feishu.cn/base/A24bb4YskaQmF4sRyAOcJacUnbb?table=tbldLkeXhonBPmXc&view=vewHhAPwRp

## 基础组件

https://github.com/idea2app/MobX-RESTful-table#pagination-table

## 参考代码

https://github.com/idea2app/Next-Bootstrap-ts/blob/069ae70bae8bdd19377bca4f57b8929804ef3bed/pages/pagination.tsx#L64-L74

**Comment by luojiyin1987** [comment]
是否在飞书的多维表单填写， 然后在官网的页面显示？
