### ISSUE TITLE
How to run the website locally step by step? 

### ISSUE THREAD

**Issue by wjsvec** [kaiyuanshe/kaiyuanshe.github.io#138]
```
npm run dev
```
looks not ok, here is the Error page:

![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/39830125/5f3e7fb2-08be-4892-afa0-0a4435c990fd)

**Comment by wjsvec** [comment]
Now with another error

![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/39830125/d99aaf8b-1460-4e70-9da1-7009f0562bae)

**Comment by tianheg** [comment]
You need a `.env.local` file which is located a private repo https://github.com/kaiyuanshe/service-configuration/blob/main/kaiyuanshe.github.io/.env.local , if you want to contribute to this repo, you can be a volunteer for KaiYuanShe community first. Click [here](https://kaiyuanshe.feishu.cn/share/base/shrcnfO89tYlYIjZpS5PXJBaK2f) to fill in the volunteer application form.

**Comment by wjsvec** [comment]
> You need a `.env.local` file which is located a private repo https://github.com/kaiyuanshe/service-configuration/blob/main/kaiyuanshe.github.io/.env.local , if you want to contribute to this repo, you can be a volunteer for KaiYuanShe community first. Click [here](https://kaiyuanshe.feishu.cn/share/base/shrcnfO89tYlYIjZpS5PXJBaK2f) to fill in the volunteer application form.
> 
> A little advice:
> 
> Use `npm install` instead of `sudo npm install`, because use `sudo` may cause permission problems.
> 
> Specific to this repo, Pnpm is recommended. Here is the installation process:
> 
> ```shell
> npm install -g pnpm
> pnpm dev
> ```

Thanks a lot, I got it! 🥰

**Comment by wjsvec** [comment]
I will try to be a volunteer☺️
