### ISSUE TITLE
COSCon'23 官网 CFP 页面增加中英文切换能力

### ISSUE THREAD

**Issue by jueduizone** [kaiyuanshe/kaiyuanshe.github.io#142]
建议 [COSCon'23 官网](https://kaiyuanshe.cn/activity/recVnSz8ru)以下组件建议增加中英文切换能力或英文入口

- [ ] CFP 页面
- [ ] 议题课件提交
- [ ] 报销申请

翻译建议找 @思颖 姐沟通

**Comment by TechQuery** [comment]
@cynbarby 翻译目标表单：https://kaiyuanshe.feishu.cn/base/A24bb4YskaQmF4sRyAOcJacUnbb?table=tblht0rkACwxtSq3&view=vewE6CkEU9
