### ISSUE TITLE
GitHub 组织 issue 全览看板页

### ISSUE THREAD

**Issue by TechQuery** [kaiyuanshe/kaiyuanshe.github.io#147]
## 基本功能

1. 分组展示各仓库还未关闭的 issue，最老的排前面
2. 服务端渲染，并启用缓存

## 后端接口

1. https://docs.github.com/zh/rest/repos/repos#list-organization-repositories
2. https://docs.github.com/zh/rest/issues/issues#list-repository-issues

## 参考代码

将以下模块中的 language 查询替换为 issue 查询即可：

https://github.com/idea2app/Next-Bootstrap-ts/blob/c8e42a8634054c73588f9f403bb5b823d507ee95/models/Repository.ts

**Comment by Guanngxu** [comment]
```shell
# repos
curl -L https://api.github.com/orgs/kaiyuanshe/repos

# issues
curl -L https://api.github.com/repos/kaiyuanshe/kaiyuanshe.github.io/issues
```

**Comment by Guanngxu** [comment]
**1、直接请求`https://api.github.com/orgs/kaiyuanshe/repos`可以得到开源社所有 repo**
![img_v2_1867c114-56a9-4754-a3e5-1638920ff99g](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/24446756/45310fc9-281a-45cb-b7b6-43600a636396)

**2、再根据每个 repo 获取其中的 issues，获取 issues 如：`https://api.github.com/repos/kaiyuanshe/kaiyuanshe.github.io/issues`**
![img_v2_34be0dbb-8e70-4e1e-88f2-2579c2b2550g](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/24446756/d6b66fa8-5813-43a9-b53d-31cf058913cd)

**repo 和 issues 结构与`kaiyuanshe.cn`中`正式成员`结构一致，即两级结构，再程序中使用嵌套循环即可**
![img_v2_dd0906d5-1a92-40d4-8877-b3083fed581g](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/24446756/2bfb30b4-bf81-4443-a88a-ff22d3170ac6)
