### ISSUE TITLE
活动志愿者列表页

### ISSUE THREAD

**Issue by TechQuery** [kaiyuanshe/kaiyuanshe.github.io#151]
## 界面参考

https://kaiyuanshe.cn/member

## 数据库表

https://kaiyuanshe.feishu.cn/base/A24bb4YskaQmF4sRyAOcJacUnbb?table=tblO8vWSjJVi1qpk&view=vewJ6uqB63

### 模型声明

https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/d905fe178c52db2c5256b0565107d5ae264dc2a4/models/Place.ts#L19-L23

### 模型关联

https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/d905fe178c52db2c5256b0565107d5ae264dc2a4/models/Activity.ts#L157-L158

### 服务端渲染数据加载

https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/d905fe178c52db2c5256b0565107d5ae264dc2a4/pages/activity/%5Bid%5D/index.tsx#L42-L48

**Comment by luojiyin1987** [comment]
有2个疑问

1.  志愿者 是 person 里面的一个角色， 还要建  Volunteer 表？
2.  是显示所有的志愿者？  还是根据活动显示志愿者？
@TechQuery

**Comment by TechQuery** [comment]
> 有2个疑问
> 
> 1.  志愿者 是 person 里面的一个角色， 还要建  Volunteer 表？
> 2.  是显示所有的志愿者？  还是根据活动显示志愿者？
> @TechQuery 

1. 通过一个角色字段来筛选，就是为了不建一个新表。
2. 请仔细看任务卡的标题和源数据的位置，肯定是活动志愿者。

**Comment by luojiyin1987** [comment]
筛选角色字段是请求前发送筛选选项， 还是全量返回数据后，再筛选？   @TechQuery

**Comment by TechQuery** [comment]
> 筛选角色字段是请求前发送筛选选项， 还是全量返回数据后，再筛选？   @TechQuery 

之前，参考：

https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/ba8e396aa190896aaa8a3dee0f9eac654dfce5b3/pages/article/index.tsx#L28-L28
