### ISSUE TITLE
参会打卡功能

### ISSUE THREAD

**Issue by TechQuery** [kaiyuanshe/kaiyuanshe.github.io#153]
## 业务逻辑

1. 参会者登录开源社官网（基于手机号、短信密码的统一登录框）

2. 参会者打开当前收听的演讲、学习的工作坊、参观的展位之议程详情页，点击『打卡』按钮显示由当前页网址（带有个人标识参数）生成的二维码。

3. 讲师、展商、分论坛出品人/主持人/志愿者确认该参会者满足自己所负责议程的打卡条件，就用手机扫描个人打卡二维码，在打开的网页中登录并点击『确认打卡』按钮。
    - 活动期间用固定的 App 扫码，在其打开的浏览器上登录一次即可长期保持登录状态
    - 上述打卡审核人的账号权限，由当前登录手机号与议程记录关联的人员信息比对后自动确定

4. 确认打卡后的数据记录在自有数据库，并将个人和整个活动的打卡数据呈现在一个页面上。

5. 个人打卡数据旁也可显示活动奖品，便于参会者兑换。

**Comment by PapayaHUANG** [comment]
可以参照： https://github.com/IdeaMall/mini-app/blob/master/src/components/SessionBox.tsx
