### ISSUE TITLE
Adding KCC members photo wall (like fCC does)

### ISSUE THREAD

**Issue by tedliu1** [kaiyuanshe/kaiyuanshe.github.io#163]
在今天的项目委会会议里面，我看到了 [fCC 的成员照片墙][1]，我觉得很棒，KCC 能不能够也照样来做一个?

[1]: https://fcc-china.vercel.app/organizer

**Comment by TechQuery** [comment]
- 数据存储：新建一个多维表格专门存储城市社区及其成员信息
- 前端界面：参考 https://fcc-china.vercel.app/ 各写一个城市社区列表、详情页

**Comment by huoyueyuyuan** [comment]
> * 数据存储：新建一个多维表格专门存储城市社区及其成员信息
> * 前端界面：参考 https://fcc-china.vercel.app/ 各写一个城市社区列表、详情页

需要确认的几个问题： 
1、kcc 的成员，目前已经提供了照片吗？哪里可以获取到kcc成员的照片。
2、如果参照社区列表， 那么是否 要给城市 一个logo图片 ，这了有指定吗？

**Comment by TechQuery** [comment]
> 需要确认的几个问题： 
> 1、kcc 的成员，目前已经提供了照片吗？哪里可以获取到kcc成员的照片。
> 2、如果参照社区列表， 那么是否 要给城市 一个logo图片 ，这了有指定吗？ 

以上全来自新建的多维表格，由@d-ethan3 完成这项工作。
