### ISSUE TITLE
请在首页置顶加个 COSCon'23 的 banner

### ISSUE THREAD

**Issue by tedliu1** [kaiyuanshe/kaiyuanshe.github.io#180]
请在首页置顶加个 COSCon'23 的 banner

**Comment by wangrunlin** [comment]
建议在主页上显示最新的一个或三个活动，类似最新文章的模块

**Comment by TechQuery** [comment]
@wangrunlin 可用上游库[轮播图组件][1]在顶部展示最新 3 个活动、3 篇文章。
https://react-bootstrap.github.io/docs/components/carousel/
