### ISSUE TITLE
活动页面移动端样式优化

### ISSUE THREAD

**Issue by wangrunlin** [kaiyuanshe/kaiyuanshe.github.io#184]
## 每个活动的人员在移动端的样式优化

<img width="317" alt="image" src="https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/64216877/66ad3017-cc00-4892-b728-aabe54f553f2">

### 代码

https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/0869640227543d619fa0dd7e5621c9c47a97e532/pages/activity/%5Bid%5D/index.tsx#L160-L170

### 技术方案

- [Breakpoints](https://getbootstrap.com/docs/5.3/layout/breakpoints/)

**Comment by luojiyin1987** [comment]
跟  媒体查询（media query) 有什么差别？

**Comment by wangrunlin** [comment]
> 跟 媒体查询（media query) 有什么差别？

代码量会少很多，具体实现也是采用的媒体查询，只是 `Bootstrap` 统一处理了
