### ISSUE TITLE
活动数据库没有数据时页面报错

### ISSUE THREAD

**Issue by wangrunlin** [kaiyuanshe/kaiyuanshe.github.io#187]
## 影响页面

含有数据库，但表格不全的页面

### 链接
- [台湾开源人年会 2023 中国大陆讲师团](https://kaiyuanshe.cn/activity/reccXEzAdL)
- [2021 第六届中国开源年会（COSCon'21）](https://kaiyuanshe.cn/activity/recoZ6PJXe)
- [2020 中国开源年会暨阿帕奇中国路演](https://kaiyuanshe.cn/activity/recYi9rLaH)
- [COSCon 2019 爱你所爱，无问西东！](https://kaiyuanshe.cn/activity/recmgqmI54)
- ……

## 报错信息

<img width="961" alt="image" src="https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/64216877/1f3fdb89-d201-41dc-b83d-028fe2eeddbe">

## 代码

https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/0869640227543d619fa0dd7e5621c9c47a97e532/models/Activity/index.ts#L164-L177

**Comment by TechQuery** [comment]
已安排@d-ethan3 同步往年数据库结构，以后**多维表格模板**创建的活动都是合格的数据结构。

**Comment by d-ethan3** [comment]
> ## 影响页面
> 含有数据库，但表格不全的页面
> 
> ### 链接
> * [台湾开源人年会 2023 中国大陆讲师团](https://kaiyuanshe.cn/activity/reccXEzAdL)
> * [2021 第六届中国开源年会（COSCon'21）](https://kaiyuanshe.cn/activity/recoZ6PJXe)
> * [2020 中国开源年会暨阿帕奇中国路演](https://kaiyuanshe.cn/activity/recYi9rLaH)
> * [COSCon 2019 爱你所爱，无问西东！](https://kaiyuanshe.cn/activity/recmgqmI54)
> * ……
> 
> ## 报错信息
> <img alt="image" width="961" src="https://user-images.githubusercontent.com/64216877/269995914-1f3fdb89-d201-41dc-b83d-028fe2eeddbe.png">
> ## 代码
> https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/0869640227543d619fa0dd7e5621c9c47a97e532/models/Activity/index.ts#L164-L177

我已经完成数据结构同步，但页面依然无法访问，不清楚是否与其他年份 COSCon 数据库里 Place 表内无数据有关。

**Comment by TechQuery** [comment]
> > ## 影响页面
> > 含有数据库，但表格不全的页面
> > ### 链接
> > 
> > * [台湾开源人年会 2023 中国大陆讲师团](https://kaiyuanshe.cn/activity/reccXEzAdL)
> > * [2021 第六届中国开源年会（COSCon'21）](https://kaiyuanshe.cn/activity/recoZ6PJXe)
> > * [2020 中国开源年会暨阿帕奇中国路演](https://kaiyuanshe.cn/activity/recYi9rLaH)
> > * [COSCon 2019 爱你所爱，无问西东！](https://kaiyuanshe.cn/activity/recmgqmI54)
> > * ……
> > 
> > ## 报错信息
> > <img alt="image" width="961" src="https://user-images.githubusercontent.com/64216877/269995914-1f3fdb89-d201-41dc-b83d-028fe2eeddbe.png">
> > ## 代码
> > https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/0869640227543d619fa0dd7e5621c9c47a97e532/models/Activity/index.ts#L164-L177
> 
> 我已经完成数据结构同步，但页面依然无法访问，不清楚是否与其他年份 COSCon 数据库里 Place 表内无数据有关。

这就是找不到表的报错，具体是哪个活动，都发出来。

**Comment by d-ethan3** [comment]
> > > ## 影响页面
> > > 含有数据库，但表格不全的页面
> > > ### 链接
> > > 
> > > * [台湾开源人年会 2023 中国大陆讲师团](https://kaiyuanshe.cn/activity/reccXEzAdL)
> > > * [2021 第六届中国开源年会（COSCon'21）](https://kaiyuanshe.cn/activity/recoZ6PJXe)
> > > * [2020 中国开源年会暨阿帕奇中国路演](https://kaiyuanshe.cn/activity/recYi9rLaH)
> > > * [COSCon 2019 爱你所爱，无问西东！](https://kaiyuanshe.cn/activity/recmgqmI54)
> > > * ……
> > > 
> > > ## 报错信息
> > > <img alt="image" width="961" src="https://user-images.githubusercontent.com/64216877/269995914-1f3fdb89-d201-41dc-b83d-028fe2eeddbe.png">
> > > ## 代码
> > > https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/0869640227543d619fa0dd7e5621c9c47a97e532/models/Activity/index.ts#L164-L177
> > 
> > 
> > 我已经完成数据结构同步，但页面依然无法访问，不清楚是否与其他年份 COSCon 数据库里 Place 表内无数据有关。
> 
> 这就是找不到表的报错，具体是哪个活动，都发出来。

目前除了 ⌈COSCon 2023⌋ 其他活动页面全挂了，水歌你看一下是我数据结构改的不正确，还是数据库链接出错了？

**Comment by TechQuery** [comment]
> 目前除了 ⌈COSCon 2023⌋ 其他活动页面全挂了，水歌你看一下是我数据结构改的不正确，还是数据库链接出错了？

本地启动开发环境，挨个点进去看是什么报错。

**Comment by d-ethan3** [comment]
> > 目前除了 ⌈COSCon 2023⌋ 其他活动页面全挂了，水歌你看一下是我数据结构改的不正确，还是数据库链接出错了？
> 
> 本地启动开发环境，挨个点进去看是什么报错。

查出是因为其他数据库缺少 Place/ Gift / Evaluation 三个表。
添加这几个表之后，页面恢复显示，但是所有议程无法显示，控制台出现以下内容
```sh
{
  code: 1254043,
  msg: 'RecordIdNotFound',
  error: { log_id: '2023101917133219435B19006377121F5A' }
}
GET https://open.feishu.cn/open-apis/bitable/v1/apps/bascnUAyhKLADcw3HyNW5OefrMd/tables/tbluBkyvww3w36jN/records/coscon-2022 200 {
  code: 1254043,
  msg: 'RecordIdNotFound',
  error: { log_id: '2023101917133219435B19006377121F5A' }
}
URIError: RecordIdNotFound
    at /home/evan/kaiyuanshe/kaiyuanshe.github.io/node_modules/.pnpm/mobx-lark@1.0.0-rc.10_mobx@6.10.2_typescript@5.1.6/node_modules/mobx-lark/dist/index.js:7:955
    at step (/home/evan/kaiyuanshe/kaiyuanshe.github.io/node_modules/.pnpm/tslib@2.6.2/node_modules/tslib/tslib.js:195:27)
    at Object.next (/home/evan/kaiyuanshe/kaiyuanshe.github.io/node_modules/.pnpm/tslib@2.6.2/node_modules/tslib/tslib.js:176:57)
    at asyncGeneratorStep (/home/evan/kaiyuanshe/kaiyuanshe.github.io/node_modules/.pnpm/@swc+helpers@0.5.3/node_modules/@swc/helpers/cjs/_async_to_generator.cjs:5:28)
    at _next (/home/evan/kaiyuanshe/kaiyuanshe.github.io/node_modules/.pnpm/@swc+helpers@0.5.3/node_modules/@swc/helpers/cjs/_async_to_generator.cjs:23:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
{
  buffer: Promise { <pending> },
  data: {
    props: {
      activity: [Object],
      currentMeta: [Object],
      forums: [],
      agendaGroup: {},
      places: []
    }
  },
  expiredAt: 1697706850548
}
```

详情截图
![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/33822639/f36e7ba9-9391-4fb0-a237-990874ce396b)

**Comment by TechQuery** [comment]
> 查出是因为其他数据库缺少 Place/ Gift / Evaluation 三个表。
> 添加这几个表之后，页面恢复显示，但是所有议程无法显示，控制台出现以下内容
> ```sh
> {
>   code: 1254043,
>   msg: 'RecordIdNotFound',
>   error: { log_id: '2023101917133219435B19006377121F5A' }
> }
> GET https://open.feishu.cn/open-apis/bitable/v1/apps/bascnUAyhKLADcw3HyNW5OefrMd/tables/tbluBkyvww3w36jN/records/coscon-2022 200 {
>   code: 1254043,
>   msg: 'RecordIdNotFound',
>   error: { log_id: '2023101917133219435B19006377121F5A' }
> }
> URIError: RecordIdNotFound
>     at /home/evan/kaiyuanshe/kaiyuanshe.github.io/node_modules/.pnpm/mobx-lark@1.0.0-rc.10_mobx@6.10.2_typescript@5.1.6/node_modules/mobx-lark/dist/index.js:7:955
>     at step (/home/evan/kaiyuanshe/kaiyuanshe.github.io/node_modules/.pnpm/tslib@2.6.2/node_modules/tslib/tslib.js:195:27)
>     at Object.next (/home/evan/kaiyuanshe/kaiyuanshe.github.io/node_modules/.pnpm/tslib@2.6.2/node_modules/tslib/tslib.js:176:57)
>     at asyncGeneratorStep (/home/evan/kaiyuanshe/kaiyuanshe.github.io/node_modules/.pnpm/@swc+helpers@0.5.3/node_modules/@swc/helpers/cjs/_async_to_generator.cjs:5:28)
>     at _next (/home/evan/kaiyuanshe/kaiyuanshe.github.io/node_modules/.pnpm/@swc+helpers@0.5.3/node_modules/@swc/helpers/cjs/_async_to_generator.cjs:23:17)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> {
>   buffer: Promise { <pending> },
>   data: {
>     props: {
>       activity: [Object],
>       currentMeta: [Object],
>       forums: [],
>       agendaGroup: {},
>       places: []
>     }
>   },
>   expiredAt: 1697706850548
> }
> ```
> 
> 详情截图
> ![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/33822639/f36e7ba9-9391-4fb0-a237-990874ce396b)
> 

请确保各表必填字段有值：

https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/2401b54847ceb6118a5fb9b9608fc28748e34b6b/models/Activity/Forum.ts#L29-L32

https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/2401b54847ceb6118a5fb9b9608fc28748e34b6b/models/Activity/Agenda.ts#L44-L60

**Comment by d-ethan3** [comment]
> > 查出是因为其他数据库缺少 Place/ Gift / Evaluation 三个表。
> > 添加这几个表之后，页面恢复显示，但是所有议程无法显示，控制台出现以下内容
> > ```
> > {
> >   code: 1254043,
> >   msg: 'RecordIdNotFound',
> >   error: { log_id: '2023101917133219435B19006377121F5A' }
> > }
> > GET https://open.feishu.cn/open-apis/bitable/v1/apps/bascnUAyhKLADcw3HyNW5OefrMd/tables/tbluBkyvww3w36jN/records/coscon-2022 200 {
> >   code: 1254043,
> >   msg: 'RecordIdNotFound',
> >   error: { log_id: '2023101917133219435B19006377121F5A' }
> > }
> > URIError: RecordIdNotFound
> >     at /home/evan/kaiyuanshe/kaiyuanshe.github.io/node_modules/.pnpm/mobx-lark@1.0.0-rc.10_mobx@6.10.2_typescript@5.1.6/node_modules/mobx-lark/dist/index.js:7:955
> >     at step (/home/evan/kaiyuanshe/kaiyuanshe.github.io/node_modules/.pnpm/tslib@2.6.2/node_modules/tslib/tslib.js:195:27)
> >     at Object.next (/home/evan/kaiyuanshe/kaiyuanshe.github.io/node_modules/.pnpm/tslib@2.6.2/node_modules/tslib/tslib.js:176:57)
> >     at asyncGeneratorStep (/home/evan/kaiyuanshe/kaiyuanshe.github.io/node_modules/.pnpm/@swc+helpers@0.5.3/node_modules/@swc/helpers/cjs/_async_to_generator.cjs:5:28)
> >     at _next (/home/evan/kaiyuanshe/kaiyuanshe.github.io/node_modules/.pnpm/@swc+helpers@0.5.3/node_modules/@swc/helpers/cjs/_async_to_generator.cjs:23:17)
> >     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> > {
> >   buffer: Promise { <pending> },
> >   data: {
> >     props: {
> >       activity: [Object],
> >       currentMeta: [Object],
> >       forums: [],
> >       agendaGroup: {},
> >       places: []
> >     }
> >   },
> >   expiredAt: 1697706850548
> > }
> > ```
> > 
> > 
> > 详情截图
> > ![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/33822639/f36e7ba9-9391-4fb0-a237-990874ce396b)
> 
> 请确保各表必填字段有值：
> 
> https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/2401b54847ceb6118a5fb9b9608fc28748e34b6b/models/Activity/Forum.ts#L29-L32
> 
> https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/2401b54847ceb6118a5fb9b9608fc28748e34b6b/models/Activity/Agenda.ts#L44-L60

因为往年 COSCon Forum 表单的 'summary' 没有值导致各论坛及所属议程无法显示。我查了百格也没有找到各论坛的简介，请问现在是取消 summary 必填，还是找到往年各论坛的简介？

**Comment by TechQuery** [comment]
> 因为往年 COSCon Forum 表单的 'summary' 没有值导致各论坛及所属议程无法显示。我查了百格也没有找到各论坛的简介，请问现在是取消 summary 必填，还是找到往年各论坛的简介？

打一个空格应该就可以

**Comment by d-ethan3** [comment]
## 可正常访问页面
- [x] [COSUP 2023](https://kaiyuanshe.cn/activity/coscup-2023)
- [x] [COSCon 2022](https://kaiyuanshe.cn/activity/coscup-2022)
- [x]  [COSCon 2021](https://kaiyuanshe.cn/activity/coscup-2021)
- [x]  [COSCon 2020](https://kaiyuanshe.cn/activity/coscup-2020)
- [x]  [COSCon 2019](https://kaiyuanshe.cn/activity/coscup-2019)
- [x]  [COSCon 2018](https://kaiyuanshe.cn/activity/coscup-2018)
- [x] [COSCon 2017](https://kaiyuanshe.cn/activity/coscup-2017)
- [x] [COSCon 2016](https://kaiyuanshe.cn/activity/coscup-2016)

## 链接失效
- [ ] [COSCon 2021 成都分场](https://kaiyuanshe.cn/activity/undefined)
- [ ] [COSCon 2020 成都分场](https://kaiyuanshe.cn/activity/undefined)

**Comment by d-ethan3** [comment]
> ## 可正常访问页面
> * [x]  [COSUP 2023](https://kaiyuanshe.cn/activity/coscup-2023)
> * [x]  [COSCon 2022](https://kaiyuanshe.cn/activity/coscon-2022)
> * [x]   [COSCon 2021](https://kaiyuanshe.cn/activity/coscon-2021)
> * [x]   [COSCon 2020](https://kaiyuanshe.cn/activity/coscon-2020)
> * [x]   [COSCon 2019](https://kaiyuanshe.cn/activity/coscon-2019)
> * [x]   [COSCon 2018](https://kaiyuanshe.cn/activity/coscon-2018)
> * [x]  [COSCon 2017](https://kaiyuanshe.cn/activity/coscon-2017)
> * [x]  [COSCon 2016](https://kaiyuanshe.cn/activity/coscon-2016)
> * [x]  [Apache RoadShow 2015](https://kaiyuanshe.cn/activity/reckOKSaJp)
> 
> ## 链接失效
> * [x]  [COSCon 2021 成都分场](https://kaiyuanshe.cn/activity/undefined)
> * [x]  [COSCon 2020 成都分场](https://kaiyuanshe.cn/activity/undefined)

已全部修复
