### ISSUE TITLE
开源问答知识库

### ISSUE THREAD

**Issue by TechQuery** [kaiyuanshe/kaiyuanshe.github.io#189]
## 关联功能

1. https://github.com/kaiyuanshe/xiaoyuan
2. #29

## 数据来源

1. https://shimo.im/sheets/BIK6IttNfRo0WVFD/gOEGJ/
2. https://github.com/kaiyuanshe/Xiaoyuan-OSS-Bot/blob/master/知识库%20(2).xlsx
3. https://kaiyuanshe.feishu.cn/wiki/RpDWwQ1VwiLfh9kMQ4FcQhXnnmh

## 后端服务

将上述数据导入一个独立的多维表格。

### 语音朗读

在官网页面加一个全局悬浮按钮，点击后随机从上述多维表格中查出一条问答显示并朗读。

#### 实现参考

- 悬浮按钮：https://wiki-map.vercel.app/#/entry/%E5%9B%9B%E5%B7%9D%E7%9C%81%20(%E4%B8%AD%E8%8F%AF%E6%B0%91%E5%9C%8B)
- 语音接口：https://tech-query.me/development/web-text-speech/

### 问答搜索

接入官网现有搜索接口：

https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/bd70ecf0f64c810b15beb14f5c9777e00d1fd349/pages/search/index.tsx#L18-L22

**Comment by luojiyin1987** [comment]
把现有数据导入多维表格， 做一个类似 kv 结构。 随机选取， 然后读出来？   @TechQuery

**Comment by TechQuery** [comment]
> 把现有数据导入多维表格， 做一个类似 kv 结构。 随机选取， 然后读出来？ @TechQuery

对的

**Comment by luojiyin1987** [comment]
要区分问题分类吗？  有问题的大类 和小类？ 
![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/6524977/2efc16e0-79fe-4c5c-b1cd-1ffbc3eccf3e)

**Comment by TechQuery** [comment]
> 要区分问题分类吗？ 有问题的大类 和小类？ ![image](https://user-images.githubusercontent.com/6524977/278964721-2efc16e0-79fe-4c5c-b1cd-1ffbc3eccf3e.png) @TechQuery

哪里有小类？
