### ISSUE TITLE
新官网加上[加入我们]

### ISSUE THREAD

**Issue by tedliu1** [kaiyuanshe/kaiyuanshe.github.io#20]
在官网里可以像微信公众号一样加个[加入我们]，便于各个项目组招募新人。

![mmexport1565877903242](https://user-images.githubusercontent.com/10952755/63100308-6405f100-bfa9-11e9-9dd6-4008cd77a959.jpg)

**Comment by moeir** [comment]
[这里][1] 已经有一个“加入我们”了，建议挪动到“成员”内。

[1]: https://kaiyuanshe.cn/governance/

**Comment by moeir** [comment]
根据讨论：

- “加入工作组”的位置不变，仍在[工作组\(治理结构\)页][1]
- “加入交流群”目前在[联系我们页][2]
- “招募”作为“成员”菜单的“加入我们”子菜单，链接到[这里][3]

[1]: https://kaiyuanshe.cn/governance/
[2]: https://kaiyuanshe.cn/profile/contact/
[3]: http://members.kaiyuanshe.cn/
