### ISSUE TITLE
部门简介新增官方电邮地址

### ISSUE THREAD

**Issue by TechQuery** [kaiyuanshe/kaiyuanshe.github.io#201]
## 原始数据

[腾讯企业邮箱][1]通讯录

## 目标数据

https://kaiyuanshe.feishu.cn/base/UaJ6b4MtcaywOwsaT7ecyiQuntc?table=tblFRxhndo7SX4a7&view=vewTLsAEW9

## 目标组件

https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/3e1d60cd4305923dd9b9e9761ab54611445187d7/components/Department/Card.tsx#L14-L53

[1]: https://exmail.qq.com/

**Comment by stevending1st** [comment]
hover 出现卡片，移除后消失，在这里添加邮箱根本就用不了。

**Comment by TechQuery** [comment]
> hover 出现卡片，移除后消失，在这里添加邮箱根本就用不了。

首先是为 #203 用的，其次如果你觉得这个地方交互有问题也可以改。
