### ISSUE TITLE
部门详情页

### ISSUE THREAD

**Issue by TechQuery** [kaiyuanshe/kaiyuanshe.github.io#203]
## 参考页面

https://kaiyuanshe.cn/member/%E7%9F%B3%E5%9E%9A

## 参考代码

https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/3e1d60cd4305923dd9b9e9761ab54611445187d7/pages/member/%5Bname%5D.tsx

## 侧栏组件

https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/3e1d60cd4305923dd9b9e9761ab54611445187d7/components/Department/Card.tsx

## 交互细节

页面做完后需连通以下链接：

1. [组织结构图][1]部门节点
2. [正式成员页][2]部门标题
3. [全局搜索页][3]部门卡片

[1]: https://kaiyuanshe.cn/department
[2]: https://kaiyuanshe.cn/member
[3]: https://kaiyuanshe.cn/search?keywords=%E5%9F%BA%E7%A1%80%E8%AE%BE%E6%96%BD

**Comment by huoyueyuyuan** [comment]
<img width="716" alt="image" src="https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/22514503/122fe22a-3e11-48e9-9b2d-b8d9a42f7e5f">
[组织结构图](https://kaiyuanshe.cn/department)部门节点 ， 这里已经存在跳转链接了，是用部门详情页替换，还是保留？

**Comment by TechQuery** [comment]
> <img width="716" alt="image" src="https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/22514503/122fe22a-3e11-48e9-9b2d-b8d9a42f7e5f">
> 
> [组织结构图](https://kaiyuanshe.cn/department)部门节点 ， 这里已经存在跳转链接了，是用部门详情页替换，还是保留？

替换

**Comment by huoyueyuyuan** [comment]
<img width="656" alt="image" src="https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/22514503/a2177b5a-101a-49da-a61f-05234864c8a0">
2个问题：
1、tag 的 href， 是否继续保留 ？ 
2、是否在 h3  就是name这里添加跳转链接 就够了， 还是要加在 外面的 div层 ？

**Comment by TechQuery** [comment]
> <img width="656" alt="image" src="https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/22514503/a2177b5a-101a-49da-a61f-05234864c8a0">
> 
> 2个问题：
> 1. tag 的 `href`， 是否继续保留？ 
> 2. 是否在 `h3` 就是 name 这里添加跳转链接 就够了， 还是要加在外面的 `div` 层？ 

1. 为什么要删掉呢？
2. 部门跳转不在标题上，因为在组织架构图中不是每个节点都会展开这张卡，所以需要从节点上跳转。

**Comment by huoyueyuyuan** [comment]
今天这个问题，不是组织架构图了。
是在搜索页这里。
根据keywords搜索出来的部门列表展示



---- 回复的原邮件 ----
| 发件人 | South ***@***.***> |
| 日期 | 2023年11月28日 10:30 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [kaiyuanshe/kaiyuanshe.github.io] 部门详情页 (Issue #203) |

image.png (view on web)

2个问题：

tag 的 href， 是否继续保留？
是否在 h3 就是 name 这里添加跳转链接 就够了， 还是要加在外面的 div 层？
为什么要删掉呢？
部门跳转不在标题上，因为在组织架构图中不是每个节点都会展开这张卡，所以需要从节点上跳转。

**Comment by TechQuery** [comment]
> 今天这个问题，不是组织架构图了。 是在搜索页这里。 根据keywords搜索出来的部门列表展示

卡片上有其它链接，暂时还是在标题上做链接。

你顺便看一下部门搜索的 API 调用，我搜“基础设施”和“项目委员会”都搜不出来。

**Comment by huoyueyuyuan** [comment]
这个问题我发现了，并已经修复了，
就是部门详情页还没完全做好。
现在上班，时间少了。没那么及时



---- 回复的原邮件 ----
| 发件人 | South ***@***.***> |
| 日期 | 2023年11月28日 10:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [kaiyuanshe/kaiyuanshe.github.io] 部门详情页 (Issue #203) |

今天这个问题，不是组织架构图了。 是在搜索页这里。 根据keywords搜索出来的部门列表展示

卡片上有其它链接，暂时还是在标题上做链接。

你顺便看一下部门搜索的 API 调用，我搜“基础设施”和“项目委员会”都搜不出来。

**Comment by TechQuery** [comment]
> 这个问题我发现了，并已经修复了， 就是部门详情页还没完全做好。 现在上班，时间少了。没那么及时

可以先把写好的部分代码推上来，创建 PR 并关联这个 issue，我可以先做一部分 review。
