### ISSUE TITLE
开源社官网流量分析

### ISSUE THREAD

**Issue by tedliu1** [kaiyuanshe/kaiyuanshe.github.io#207]
看看哪一位将 Google Analytics 调用来分析开源社官网的流量

**Comment by luojiyin1987** [comment]
用谁的 ID ？  Google Analytics 在国内可能被屏蔽，需要做转发。  然后是数据出境问题， 数据要去标识化，要做模糊化，匿名化。

**Comment by TechQuery** [comment]
> 用谁的 ID ？  Google Analytics 在国内可能被屏蔽，需要做转发。  然后是数据出境问题， 数据要去标识化，要做模糊化，匿名化。

已申请 ID，私发你。

我个站、fCC 成都社区都用的 Google 分析，感觉没问题。

访问统计本来就是匿名的吧？
