### ISSUE TITLE
【开源社项目】页面修改为手动维护

### ISSUE THREAD

**Issue by stevending1st** [kaiyuanshe/kaiyuanshe.github.io#210]
页面如下：https://kaiyuanshe.cn/project

**Comment by stevending1st** [comment]
> 首先要将所有 Git 仓库同步到自有数据库，再在自有数据库用一个字段排序。这样设计很复杂，且对现有工作没啥实质帮助。

一个合理方式是手动修改配制文件，而非从 github 爬取。

**Comment by TechQuery** [comment]
> 一个合理方式是手动修改配制文件，而非从 github 爬取。

这是 2019 版官网采用的方式，最终都是我一个人在维护，其它程序员都懒得搞清楚怎么改数据。
 
> 无需生成首页，直接跳转 GitHub Repo 首页就好。

那和 GitHub 组织主页就没区别了，而且 `github.com` 墙内访问困难，`github.io` 访问还相对流畅，而且官网主要就是面向墙内用户的。

**Comment by luojiyin1987** [comment]
> > 一个合理方式是手动修改配制文件，而非从 github 爬取。
> 
> 这是 2019 版官网采用的方式，最终都是我一个人在维护，其它程序员都懒得搞清楚怎么改数据。
> 
> > 无需生成首页，直接跳转 GitHub Repo 首页就好。
> 
> 那和 GitHub 组织主页就没区别了，而且 `github.com` 墙内访问困难，`github.io` 访问还相对流畅，而且官网主要就是面向墙内用户的。

现在改为服务端转发客户端的请求，保障服务端可以访问 `github.io` 就可以了。  为什么要手动维护？ 按照 star 数 更新时间  自动排序不行？ @stevending1st
