### ISSUE TITLE
COSCon 官网更新  2023 年赞助信息

### ISSUE THREAD

**Issue by stevending1st** [kaiyuanshe/kaiyuanshe.github.io#214]

**Comment by TechQuery** [comment]
在此录入：https://kaiyuanshe.feishu.cn/share/base/form/shrcnby24AwnVChEgl62f3u8JTb

**Comment by stevending1st** [comment]
> 在此录入：https://kaiyuanshe.feishu.cn/share/base/form/shrcnby24AwnVChEgl62f3u8JTb

《开源社合作关系登记》需新增“特别支持”一级，显示在星牌之下

**Comment by TechQuery** [comment]
> @TechQuery 
> 1. 《开源社合作关系登记》需新增“特别支持”一级，显示在星牌之下
> 2. 如果赞助商替换“名称”如何处理？
> 3. 白金席位需单排列出（一个 Logo 一行）

1. 表中新增选项后，再在代码中增加：
https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/23dd04aca30b1566da75d3866608a3b248c0f0b8/pages/organization/cooperation.tsx#L27-L28

2. 不明白为何要改名，如果已经是不同的公司主体，请新增一个组织。

3. 都是白金，谁排上边？很难一碗水端平，还是同一行妥当。

**Comment by stevending1st** [comment]
> 3. 都是白金，谁排上边？很难一碗水端平，还是同一行妥当。
这个是合同的权益——单排显示，可以按字母排序

**Comment by stevending1st** [comment]
> > 3. 都是白金，谁排上边？很难一碗水端平，还是同一行妥当。

这个是合同的权益——单排显示，可以按字母排序

**Comment by TechQuery** [comment]
> > > 3. 都是白金，谁排上边？很难一碗水端平，还是同一行妥当。
> 
> 这个是合同的权益——单排显示，可以按字母排序，参考：
> ![20231014-230113](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/23376142/63c11a15-a9a2-411a-a6ae-7b708cbc25b2)

改这里：
https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/23dd04aca30b1566da75d3866608a3b248c0f0b8/pages/organization/cooperation.tsx#L68-L72
