### ISSUE TITLE
无效链接 - 许可证选择器

### ISSUE THREAD

**Issue by htynkn** [kaiyuanshe/kaiyuanshe.github.io#22]
<img width="301" alt="屏幕快照 2019-09-04 下午3 53 49" src="https://user-images.githubusercontent.com/659135/64236107-4edb0d00-cf2c-11e9-922f-00c6b722f880.png">

链接地址：https://kaiyuanshe.cn/license-tool.html 访问404

**Comment by robyle** [comment]
@TechQuery  该页面我提交测试下基础html内容,麻烦你那边看下。

**Comment by robyle** [comment]
@TechQuery 我再次调整了下位置，许可证选择器当前是可用状态。麻烦你那边看下，然后看下如何在静态页面上增加下头部和尾部。

**Comment by TechQuery** [comment]
ce59fa6

**Comment by TechQuery** [comment]
> @TechQuery 我再次调整了下位置，许可证选择器当前是可用状态。麻烦你那边看下，然后看下如何在静态页面上增加下头部和尾部。

3f6a952
