### ISSUE TITLE
官网文章需求

### ISSUE THREAD

**Issue by d-ethan3** [kaiyuanshe/kaiyuanshe.github.io#227]
1. 需要在官网文章里放上原微信公众号相应文章的链接
2. 在微信公众号发布时，上方的合集可以点击，并通过合集看到这一合集里的所有文章。
     - 在官网同步后，官网文章里的合集标签无法点击，需要解决这一问题。   

@王玥敏

**Comment by wangrunlin** [comment]
> 2. 在微信公众号发布时，上方的合集可以点击，并通过合集看到这一合集里的所有文章。

1. 媒体组添加和合集对应的标签
2. 文章详情界面添加标签按钮
