### ISSUE TITLE
新模块：大会日程安排

### ISSUE THREAD

**Issue by moeir** [kaiyuanshe/kaiyuanshe.github.io#23]
一个类似于 sched 的大会日程安排的展示、订阅、提醒项目。

目前的设想如下：

- 会议组织者：发布/管理大会日程
- 访客：查看日程，筛选日程
- 注册会员：订阅日程，获得订阅的日历（CalDAV）

**Comment by TechQuery** [comment]
http://www.dukecon.org/links.html

**Comment by TechQuery** [comment]
前两项需求已由以下项目实现：
 - 后端仓库：https://github.com/kaiyuanshe/service
 - 前端仓库：https://github.com/kaiyuanshe/PWA
 - 线上环境：http://coscon.kaiyuanshe.cn/

目前上述系统也可用 **GitHub 账号登录**，但须实现**日程订阅**、**iCal 文件生成**功能，可[去前端仓库提 issue](https://github.com/kaiyuanshe/PWA/issues/new)。
