### ISSUE TITLE
议程页面优化

### ISSUE THREAD

**Issue by WallaceOS** [kaiyuanshe/kaiyuanshe.github.io#230]
1. 出品人照片大小和讲师一致（目前出品人偏小）
2. 出品人和讲师显示的介绍均包括单位和职务（目前是出品人只显示职务、讲师只显示单位）
3. 讲师议题点进去后增加讲师详细介绍的显示（例如显示在下图红框位置处，目前只显示议题内容详细介绍）

![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/37771051/6589d831-e9db-47b5-b389-f0c334d1e77b)

**Comment by PapayaHUANG** [comment]
@WallaceOS 第三条指的讲师介绍是讲师的职位和公司吗？所以第三条是第二条的子集？

**Comment by WallaceOS** [comment]
不是的，讲师介绍是讲师信息里一个专门的字段，里面有讲师的详细介绍（不只是职位和公司）










--

在 2023-10-20 12:11:45，"Shaoya HUANG" ***@***.***> 写道：

@WallaceOS 第三条指的讲师介绍是讲师的职位和公司吗？所以第三条是第二条的子集？
