### ISSUE TITLE
[UI优化]COSCon'23主页面出品人单位显示不全

### ISSUE THREAD

**Issue by Nliver** [kaiyuanshe/kaiyuanshe.github.io#231]
## issue
![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/34496563/62f97b3e-82c0-4c3a-ba20-92097dcaa32e)

出品人的单位没有显示

## PRD
建议显示完全出品人的单位

**Comment by TechQuery** [comment]
与 #230 重复
