### ISSUE TITLE
许可证选择器优化

### ISSUE THREAD

**Issue by tedliu1** [kaiyuanshe/kaiyuanshe.github.io#234]
@luojiyin1987 
1. 关于传染性的用法，建议可以修改为 ”强互惠/强传染 or 弱互惠/弱传染“？
2. 建议在做完选择后可以回滚（roll-baclk），如此可以方便回到上一步重新选择？
3. 建议在 ”筛选条件“ 的下方加上标题，例如
    - 第一步的标题是 ”**流行程度**“，
    - 其说明为：”您是否希望将结果限制在开放源代码促进会（Open Source Initiative, 缩写: OSI）所描述的 "流行、广泛使用或拥有强大社群” 的许可证上？为了确保许可协议为主流许可协议，将妥协放弃掉一些不那么主流但可能有用的特征。“

https://github.com/kaiyuanshe/kaiyuanshe.github.io/commit/c35cec63bdb0c071ef0e3c055e481280b6c80267#commitcomment-130605205

**Comment by luojiyin1987** [comment]
关于传染性的用法，建议可以修改为 ”强互惠/强传染 or 弱互惠/弱传染“？ 
我可以再改一下

建议在做完选择后可以回滚（roll-baclk），如此可以方便回到上一步重新选择？
是全部重置？ 还是 做一个 上一步   ？ 

建议在 ”筛选条件“ 的下方加上标题
这可以再调整

@tedliu1

**Comment by tedliu1** [comment]
能回到 “上一步” 即可 🫡

**Comment by luojiyin1987** [comment]
关于传染性的用法，建议可以修改为 ”强互惠/强传染 or 弱互惠/弱传染“？ 
已经改成
`您是否想选择强传染(强互惠)的协议？当您选择强传染(强互惠)许可证时，任何使用、修改或分发您的代码的人都必须遵循相同的许可证要求。这意味着他们必须提供源代码，并将其代码以相同的许可证发布。这样，您的代码的开放性将被保护，并且任何人都可以获得您的代码的源代码，以便进行学习、改进和共享。强传染性许可证确保了对整个项目的开放性和共享性，促进了开源社区的合作和创新。但是，选择强传染性许可证可能会对某些开发者或组织造成限制。`

@tedliu1

**Comment by tedliu1** [comment]
@luojiyin1987 能将强互惠(强传染)放在前面吗？

**Comment by luojiyin1987** [comment]
已经变更为
`您是否想选择强互惠(强传染)的协议？当您选择强互惠(强传染)许可证时，任何使用、修改或分发您的代码的人都必须遵循相同的许可证要求。这意味着他们必须提供源代码，并将其代码以相同的许可证发布。这样，您的代码的开放性将被保护，并且任何人都可以获得您的代码的源代码，以便进行学习、改进和共享。强互惠(强传染)许可证确保了对整个项目的开放性和共享性，促进了开源社区的合作和创新。但是，选择强互惠(强传染)许可证可能会对某些开发者或组织造成限制。`
@tedliu1

**Comment by tedliu1** [comment]
太棒了，谢谢 @luojiyin1987
