### ISSUE TITLE
【优化】移动端适配

### ISSUE THREAD

**Issue by dethan3** [kaiyuanshe/kaiyuanshe.github.io#236]
- [x] 在移动端下 [Roundtable Discussion] 标识溢出

![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/33822639/404a1f2c-0a02-46cf-beb3-199036576c87)

**Comment by wangrunlin** [comment]
- [ ] 活动页面按钮文字不换行

![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/64216877/e44bfa92-cb87-464b-a647-a626fb0770ac)

**Comment by wangrunlin** [comment]
- [ ] 打卡按钮修改为 hover

![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/64216877/52879da8-1049-4f7d-b4cb-b2ee3b0cb308)
![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/64216877/0e076ed0-4d12-4c05-8992-321497ea4570)

**Comment by wangrunlin** [comment]
- [ ] 议程详情页面文件文本溢出
![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/64216877/059fec30-c900-48c1-a815-7b9842232ff6)

**Comment by zshnb** [comment]
剩下几个修好了吗，没修好可以让我继续修复吗， @wangrunlin @Five-great

**Comment by TechQuery** [comment]
> 剩下几个修好了吗，没修好可以让我继续修复吗， @wangrunlin @Five-great

@zshnb 可以一次性修复多个小问题，但注意用主仓库，不要用 fork 了，否则 PR 检测不出构建错误：
![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/19969570/7ca7d529-77c2-41d1-ad57-7977370cb428)

**Comment by TechQuery** [comment]
- [ ] 手机端活动主页头图太大，请还原以前的样式

@zshnb 

### 现状

![IMG_20231128_105035.jpg](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/19969570/52573aa7-bec8-482f-b417-9e23f64ff648)

### 旧貌
 [image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/64216877/e44bfa92-cb87-464b-a647-a626fb0770ac)

**Comment by zshnb** [comment]
@TechQuery 这个修复在pr里了，一直没来得及合并

**Comment by TechQuery** [comment]
> @TechQuery 这个修复在pr里了，一直没来得及合并

@zshnb 已合并，改完哪些就在上面打钩，然后可以继续修复其它适配问题。
