### ISSUE TITLE
官网-组织架构参考 fCC 模式改造

### ISSUE THREAD

**Issue by tedliu1** [kaiyuanshe/kaiyuanshe.github.io#240]
之前水歌曾经展示过 fCC 官网里展示了成员的介绍和头像，非常活泼。希望能参考并与成员发展组携手改造目前官网上组织架构的呈现。至少要有头像及个人介绍。

freeCodeCamp 中文社区 https://fcc-china.vercel.app/

**Comment by TechQuery** [comment]
早已实现，只不过他们都不填信息罢了，示例详见：
https://kaiyuanshe.cn/member/%E7%9F%B3%E5%9E%9A

**Comment by d-ethan3** [comment]
> #88 早已实现，只不过他们都不填信息罢了，示例详见： https://kaiyuanshe.cn/member/%E7%9F%B3%E5%9E%9A

看了下你的 [详情页](https://kaiyuanshe.cn/member/%E7%9F%B3%E5%9E%9A) 还是获取了 github 个人页面的头像，不是 [开源社人事数据库](https://kaiyuanshe.feishu.cn/wiki/GTPYwjKu2iHHX6kHq9dcPYW8nkd?table=tblktfzAW8uNOVvR)  Person 表 avatar 字段下的文件。

**Comment by TechQuery** [comment]
> > #88 早已实现，只不过他们都不填信息罢了，示例详见： https://kaiyuanshe.cn/member/%E7%9F%B3%E5%9E%9A
> 
> 看了下你的 [详情页](https://kaiyuanshe.cn/member/%E7%9F%B3%E5%9E%9A) 还是获取了 github 个人页面的头像，不是 [开源社人事数据库](https://kaiyuanshe.feishu.cn/wiki/GTPYwjKu2iHHX6kHq9dcPYW8nkd?table=tblktfzAW8uNOVvR)  Person 表 avatar 字段下的文件。

那是因为在大家都没传头像时的权益之计

**Comment by stevending1st** [comment]
@tedliu1 似乎这个可以和 KCC 一起~

**Comment by TechQuery** [comment]
@tedliu1 @dethan3 以下最近完成的任务卡已补全本卡构想：
- #203
- #239
