### ISSUE TITLE
空值添加防御性代码

### ISSUE THREAD

**Issue by wangrunlin** [kaiyuanshe/kaiyuanshe.github.io#245]
- 可使用其他页面添加测试数据
- 数据异常时页面正常显示，只是对应卡片数据为空

- [ ] 议程 type 空值判断

**Comment by TechQuery** [comment]
直接编辑表格任何一个字段都可能为空，那我们要加的空值防御就太多了，代码就变成屎山了。

这就是为什么让大家一定要用生成的表单来填，上面明确控制了哪些是必填的。

前面几个月的演示和培训会不上，各种临阵抱佛脚，乱搞数据，这个锅代码可不背。

**Comment by TechQuery** [comment]
进一步修复： 3a22a64
