### ISSUE TITLE
移动端菜单样式优化

### ISSUE THREAD

**Issue by wangrunlin** [kaiyuanshe/kaiyuanshe.github.io#248]
- [ ] 点击子菜单后，文本居中显示

![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/64216877/bbd81901-4f11-46e3-81bf-0b12325ea86b)

**Comment by PapayaHUANG** [comment]
@wangrunlin 子菜单的文本也居中吗？还是只居中下拉菜单标题？

**Comment by wangrunlin** [comment]
下拉菜单的标题按原本未点击状态显示

**Comment by PapayaHUANG** [comment]
> 下拉菜单的标题按原本未点击状态显示
![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/70144378/4e893596-4009-4e8d-8614-dcac43c9ffa2)
最后呈现成这个样子？

**Comment by PapayaHUANG** [comment]
> > 下拉菜单的标题按原本未点击状态显示
> > ![image](https://user-images.githubusercontent.com/70144378/277857796-4e893596-4009-4e8d-8614-dcac43c9ffa2.png)
> > 最后呈现成这个样子？
> > 就是保留了标题原本状态，同时子菜单的文本也保留了不居中 @wangrunlin

好～我测试了一下其他尺寸的页面，子菜单保留好看一些哈哈哈

**Comment by wangrunlin** [comment]
Cool，效率杠杠的 👍
