### ISSUE TITLE
许可证选择器手机版显示不一致

### ISSUE THREAD

**Issue by tedliu1** [kaiyuanshe/kaiyuanshe.github.io#262]
许可证选择器手机版显示不一致。尝试找出木兰宽松许可证，网页版显示出来，但是手机版却没有。可能是个 bug?

**Comment by luojiyin1987** [comment]
![img_v3_024p_ffd1a289-e424-4ddd-9e24-81fe1a3e6ceg](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/6524977/9c0bad2b-9b13-4506-b59a-4c7c99d24193)

![img_v3_024p_fe205f7d-9acb-4e60-b289-5ad458755dcg](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/6524977/57ee6cb7-7ab0-4038-b3f1-437d02cc718c)

我的 红米  note 11T pro 是找到了。
@tedliu1

**Comment by luojiyin1987** [comment]
![img_v3_024p_d29ac664-bc50-41c0-91cf-a373b256adag](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/6524977/7a7f9c05-aa9c-45fc-a53f-c0f86126fdc2)
第一步选择  不需要，然后往下翻。
