### ISSUE TITLE
许可证选择器的积分计算疑问？

### ISSUE THREAD

**Issue by tedliu1** [kaiyuanshe/kaiyuanshe.github.io#263]
我按照木兰宽松许可证的筛选条件逐一输入，结果最后获得了 70 分而不是 100 分？请问计算的逻辑为何？

**Comment by luojiyin1987** [comment]
![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/6524977/f7d47bad-f773-478f-98f3-9c9b432b9eed)

![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/6524977/65b255a0-a4fb-416f-9a0c-e1a5c9857d47)
这是维护的底层数据，是否与期望的一致？
@tedliu1

**Comment by tedliu1** [comment]
我是按照木兰宽松许可证的条件逐一筛选，结果不应该是 100 分吗？

**Comment by luojiyin1987** [comment]
> 我是按照木兰宽松许可证的条件逐一筛选，结果不应该是 100 分吗？
不做要求时，不算分的。木兰宽松许可证有  法律管辖、归属振强 、隐私漏洞，三个不做要求， 所以是 70 分。
@tedliu1   @TechQuery

**Comment by tedliu1** [comment]
哦哦，理解了

**Comment by TechQuery** [comment]
> 我是按照木兰宽松许可证的条件逐一筛选，结果不应该是 100 分吗？

不做要求时，不算分的。木兰宽松许可证有  法律管辖、归属振强 、隐私漏洞，三个不做要求， 所以是 70 分。
@tedliu1   @TechQuery
