### ISSUE TITLE
开源社文创推广及销售渠道

### ISSUE THREAD

**Issue by tedliu1** [kaiyuanshe/kaiyuanshe.github.io#264]
是否需要在官网上与小红书上的开源社文创做出链接？需要和媒体组设计小队来对接。

https://www.xiaohongshu.com/user/profile/6528f512000000002a018253?xhsshare=WeixinSession&appuid=5d862b3200000000010183b1&apptime=1698824252

**Comment by stevending1st** [comment]
干净链接： https://www.xiaohongshu.com/user/profile/6528f512000000002a018253
