### ISSUE TITLE
Docker compose 容器性能限制

### ISSUE THREAD

**Issue by TechQuery** [kaiyuanshe/kaiyuanshe.github.io#286]
## 参考文档

- https://docs.docker.com/compose/compose-file/compose-file-v3/#resources
- https://xobo.org/docker-limit-cpu-and-memory/
- http://blog.joylau.cn/2020/09/22/Docker-Compose-3-Mem-CPU-Limit/

**Comment by luojiyin1987** [comment]
把 docker 容器使用最大内存限制为主机的一半， 留一半的内存给别的 docker 容器，避免影响别的 docker 容器。 早点触发 OOM，早点重启 docker 容器， 早点释放内存，
