### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by wangrunlin** [kaiyuanshe/kaiyuanshe.github.io#290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

内存泄漏，会导致服务器 ssh 无法连接，整个应用程序无法访问。

### Expected Behavior

正常运行，无内存负载较高情况。

### Steps To Reproduce

正常访问页面，无其他异常操作

### On which operating system are you experiencing the problem?

Linux, Windows, MacOS, iOS, Android

### The version of your Operation System

0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Opera, Brave, Arc Browser, UC Browser

### The version of your Web browser

0

### What network region are you in?

Global, China mainland

### Which command line terminal are you using?

Shell

### Which JavaScript runtime are you using?

Node.js

### The version of your JavaScript runtime

20

### Which JavaScript package manager are you using?

pnpm

### The version of your JavaScript package manager

0

### Which development environment are you using?

Local

**Comment by wangrunlin** [comment]
@luojiyin1987 提出，可能是第三方库 [`axios`]( https://github.com/axios/axios/issues/5641) 的问题

**Comment by TechQuery** [comment]
> @luojiyin1987 提出，可能是第三方库 [`axios`]( https://github.com/axios/axios/issues/5641) 的问题

但 Axios 所在的 Guard 组件只做客户端渲染，而且在开放黑客松那边也用，都没出现过这种问题。

https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/25c27d41656d4f184b59e074b4dea99048784a43/pages/activity/%5Bid%5D/agenda/%5BagendaId%5D/index.tsx#L46-L49

**Comment by luojiyin1987** [comment]
https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/4c8864af6f001cd1d7d2f5841779f6931b6b4048/models/Base/User.ts#L1-L14  

在 User.ts 文件是有引用的

**Comment by luojiyin1987** [comment]
现在在尝试  https://www.brendangregg.com/blog/2016-07-13/llnode-nodejs-memory-leak-analysis.html   里面的思路。
