### ISSUE TITLE
增加移步新版官网的导引

### ISSUE THREAD

**Issue by WallaceOS** [kaiyuanshe/kaiyuanshe.github.io#299]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Description

目前新版网站为https://kaiyuanshe.cn/ ， https://kaiyuanshe.github.io/ 为旧版，但搜索“开源社”都会显示，如果进入了旧版网站可能会产生困扰（引用旧版错误信息，或者误以为开源社不再更新网站等）。故建议在旧版网站页面增加相关提示，例如在首页加个比较显眼的图，提示大家移步到新版官网。

**Comment by TechQuery** [comment]
推荐组件：https://getbootstrap.com/docs/5.3/components/alerts/
