### ISSUE TITLE
开源之星头像有错误 & 中国开源先锋无任何头像显示

### ISSUE THREAD

**Issue by tedliu1** [kaiyuanshe/kaiyuanshe.github.io#302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

目前显示的 2023 开源之星的当选者有问题，至少我 Ted Liu 不应该在上面。
![开源之星头像问题](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/10952755/119677d7-df63-46f9-90a8-1733910c567e)

中国开源先锋无任何头像显示
![中国开源先锋显示问题](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/10952755/8500de30-6c83-4633-b2c1-3a0e288d5b87)

### Expected Behavior

请更正为正确当选人，我印象中的当选人应该是 “丁文昊”。

### Steps To Reproduce

You can use a browser to see for yourself.

### What kind of hardware did the bug occur on?

Desktop, Phone

### On which operating system are you experiencing the problem?

Windows, Android

### The version of your Operation System

Windows 11 & Android 14

### What browsers are you seeing the problem on?

Chrome

### The version of your Web browser

Google Chrome 121.0.6167.86（正式版本） （64 位）

### What kind of network are you connecting to?

WiFi

### What network region are you in?

Global

**Comment by TechQuery** [comment]
因为所有人事数据都在同一个飞书多维表格数据库里，经过 2024 年初社内选举过程中被迫大幅修改表单项和当选条件公式，使过去其它类别的数据不满足条件而显示出错。

这个问题已在选举后指派当时的“成员发展组”来事后修正数据，但新一届执委会班子没有继续保留成员发展组，事情就搁置了……

**Comment by TechQuery** [comment]
飞书任务：https://applink.feishu.cn/client/todo/detail?guid=8116a262-d7f4-4562-a204-939ba9f03e72&suite_entity_num=t100643
