### ISSUE TITLE
<bug> 换届和纳新选举无法验证正式成员身份

### ISSUE THREAD

**Issue by Nliver** [kaiyuanshe/kaiyuanshe.github.io#303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

换届和纳新选举的系统无法验证正式成员身份

### Expected Behavior

目前投票系统存在两个严重的Bug：
1、无法验证投票人的真实身份，是一个比较严重的问题，容易造成误票。
2、投票系统理论上只能选择“赞成”或“反对”吧，不可以出现“既赞成又反对”的票呢？应该做一个限定

### Steps To Reproduce

1、验证投票人的真实身份
2、投票系统理论上只能选择“赞成”或“反对”吧，不可以出现“既赞成又反对”的票呢

### On which operating system are you experiencing the problem?

Windows

### The version of your Operation System

Win 10

### What browsers are you seeing the problem on?

Chrome

### The version of your Web browser

版本 122.0.6261.6（正式版本）beta （64 位）

### What network region are you in?

China mainland

### Which command line terminal are you using?

CMD

### Which JavaScript runtime are you using?

Node.js

### The version of your JavaScript runtime

无

### Which JavaScript package manager are you using?

Yarn

### The version of your JavaScript package manager

无

### Which development environment are you using?

Local

### Anything else?

无

**Comment by TechQuery** [comment]
感谢反馈，但用户功能层面的 bug 请使用对应类型的表单：https://github.com/kaiyuanshe/kaiyuanshe.github.io/issues/new?assignees=&labels=bug&projects=&template=bug-user.yml&title=%3Ctitle%3E
