### ISSUE TITLE
英文模式下，navbar没有正常展开

### ISSUE THREAD

**Issue by ShakalakaB** [kaiyuanshe/kaiyuanshe.github.io#307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

非手机设备打开情况下，出现以下情况
<img width="1384" alt="Screenshot 2024-02-22 at 23 10 08" src="https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/32429379/8ea8234a-bbcc-4c3b-9292-cccbb283c256">
<img width="1473" alt="Screenshot 2024-02-22 at 23 10 15" src="https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/32429379/351602b3-b1c6-4b2d-9641-9b230871a406">

### Expected Behavior

navbar应当展开

### Steps To Reproduce

1. Link: https://kaiyuanshe.cn/
2. 语言模式切换为“English"

### What kind of hardware did the bug occur on?

Desktop

### On which operating system are you experiencing the problem?

MacOS

### The version of your Operation System

macOS

### What browsers are you seeing the problem on?

Chrome

### The version of your Web browser

122.0.6261.57

### What kind of network are you connecting to?

WiFi

### What network region are you in?

Global

**Comment by TechQuery** [comment]
感谢反馈，但这恰恰是为了解决 bug 而做的 feature，详见：#167

**Comment by rakihub** [comment]
谢谢回复。
感觉用这个方式解决上述bug有点不合适，或许尝试修改英文显示内容，精简英文单词更好。
只是个人感觉，不合适请忽略。

**Comment by ShakalakaB** [comment]
谢谢回复。
感觉用这个方式解决上述bug有点不合适，或许尝试修改英文显示内容，精简英文单词更好。
只是个人感觉，不合适请忽略。

**Comment by TechQuery** [comment]
> 或许尝试修改英文显示内容，精简英文单词更好。

有好的精简建议也可以提出来。
