### ISSUE TITLE
发布：开源软件的价值（哈佛商学院研究报告-初稿）

### ISSUE THREAD

**Issue by tedliu1** [kaiyuanshe/kaiyuanshe.github.io#309]
本研究报告的中文翻译【开源软件的价值（哈佛商学院研究报告-初稿）】
https://hackmd.io/7O2fpfsAQGiFfYFEPN4eNQ?view （英文原文 40 页），目前正由国际接轨（翻译）组刘文涛老师审校中。

Ted 已向媒体组申请发布一篇【开源软件的真实价值：哈佛商学院研究报告-初稿.导读】

https://kaiyuanshe.feishu.cn/wiki/ZUdNwamCNi1iOekn108c65ftnwv

在此，我也申请将本研究报告的中文翻译在开源社官网发布。

p.s. 我已经请媒体组小编在发布导读文章前，先确认中文翻译已经审校过，并已发布到开源社官网，再进行开源社微信公众号的发布。

**Comment by TechQuery** [comment]
> 我已经请媒体组小编在发布导读文章前，先确认中文翻译已经审校过，并已发布到开源社官网，再进行开源社微信公众号的发布。

目前 2022 版官网没有启用 2019 版官网 Git 子模块 + Markdown 生成的模式，只启用了爬取外站网址的“开源文库”数据库，因此平时都是公众号先发，再同步官网。

**Comment by tedliu1** [comment]
@TechQuery 这次的研究报告翻译，我有飞书版和 Markdown 版。所以你的意思是，其实我直接用飞书版就可以发布了，是吗？

**Comment by TechQuery** [comment]
> 所以你的意思是，其实我直接用飞书版就可以发布了，是吗？

把飞书文档移动到 https://kaiyuanshe.feishu.cn/wiki/wikcn749HAOCD2dwaNq4dOC67db 即可。

**Comment by tedliu1** [comment]
@TechQuery 水歌，我在 开源社 Wiki 里没找到放置这篇研究报告翻译文的合适位置。刚刚也确认了 2023 中国开源年度报告 是放在 https://kaiyuanshe.github.io/2023-China-Open-Source-Report/。我不确定该咋做?

**Comment by TechQuery** [comment]
> 我在 开源社 Wiki 里没找到放置这篇研究报告翻译文的合适位置。

暂时没合适的，自己建一个新目录结构就行。

> 刚刚也确认了 2023 中国开源年度报告 是放在 https://kaiyuanshe.github.io/2023-China-Open-Source-Report/ 。
>
> 我不确定该咋做?

他们有独立的批量 Markdown 文件生成程序，和你这个单一文章不同。

**Comment by tedliu1** [comment]
@TechQuery 好吧，我自己创建一个 Wiki 目录吧！

**Comment by tedliu1** [comment]
@TechQuery 刚刚已经在企业微信的执委会群里提出了我的疑惑。看看后续如何操作再决定 Wiki 目录该如何建立了

**Comment by TechQuery** [comment]
> @TechQuery 貌似只有你有权限创建一个 Wiki 子目录。可以帮忙在执行委员会底下创建一个 “国际接轨组” 子目录，底下再摆一个 “翻译文档” 的孙目录吗？不确定这样的目录结构是否合适？因为所谓的国际接轨组并没有正式运作，目前只有翻译功能。

- 飞书文档：https://kaiyuanshe.feishu.cn/wiki/UMrQwhqgTih0cCk5f8jcfmSon9e
- 官网页面：https://kaiyuanshe.cn/article/The-Real-Value-of-Open-Source-Software-Harvard-Business-School-Research-Report%20-First-draft-Wechat-guide
