### ISSUE TITLE
新增功能建议：成员看板

### ISSUE THREAD

**Issue by WallaceOS** [kaiyuanshe/kaiyuanshe.github.io#314]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Description

Linux基金会的成员看板的页面https://openprofile.dev/ ，
觉得可以借鉴，将来可以和开源社成员的数据库打通。

例如通过开源社渠道报名的参加的活动，可以自动呈现到这个成员的个人页面上。

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kaiyuanshe) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kaiyuanshe/kaiyuanshe.github.io/issues/314">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kaiyuanshe/kaiyuanshe.github.io/issues/314/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kaiyuanshe/kaiyuanshe.github.io/issues/314/pledge.svg">
</picture>
</a>

**Comment by TechQuery** [comment]
> 可以主要参照这个形式有一个正式成员的个人页面，强调的信息可以基于开源社数据库已有的信息，看能够同步哪些个人信息

早就有了：https://kaiyuanshe.cn/member/%E6%A2%81%E5%B0%A7
