### ISSUE TITLE
开源年会的分论坛部分支持以出品社区展示

### ISSUE THREAD

**Issue by jueduizone** [kaiyuanshe/kaiyuanshe.github.io#325]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Description

今年的开源年会的分论坛由出品人机制改为出品社区，当前页面显示还是出品人，应该改为出品社区。

**Comment by TechQuery** [comment]
因为每年大会官网并不是单独开发，而是用统一的模板套每年不同数据来渲染的，所以我们只会在出品人头像左侧增加出品社区信息。

同时今年虽然是社区出品制，但社区主理人还是作为出品工作的核心负责人，讲师邀约还是主要靠他们的个人影响力，他们也在申办表单上填写了个人信息，因此原出品人信息依然保留也是合理的。
