### ISSUE TITLE
开源社官网的滚动图，图片中地址信息被遮挡

### ISSUE THREAD

**Issue by luojiyin1987** [kaiyuanshe/kaiyuanshe.github.io#339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

访问开源社网站首页

### Expected Behavior

开源社官网的滚动图，图片中地址信息不应该被遮挡

### Steps To Reproduce

![image](https://github.com/user-attachments/assets/2d523594-2323-4bcd-a6b2-5f562189571a)
1080p 全屏下

### What kind of hardware did the bug occur on?

Desktop

### On which operating system are you experiencing the problem?

Windows

### The version of your Operation System

Window10

### What browsers are you seeing the problem on?

Chrome

### The version of your Web browser

 129.0.6668.100

### What kind of network are you connecting to?

WLAN

### What network region are you in?

China mainland

**Comment by TechQuery** [comment]
深蓝条加一点透明度，最终让用户点进去看。
