### ISSUE TITLE
<媒体组 页面的头像是灰的，不太合适>

### ISSUE THREAD

**Issue by luojiyin1987** [kaiyuanshe/kaiyuanshe.github.io#363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://kaiyuanshe.cn/department/%E5%AA%92%E4%BD%93%E7%BB%84/2024
![image](https://github.com/user-attachments/assets/57ae7db4-18b9-4b6b-b0b4-45acc72f2f27)
人像是灰的，不太合适

### Expected Behavior

人像应该正常显示， 不是灰色的

### Steps To Reproduce

访问  https://kaiyuanshe.cn/department/%E5%AA%92%E4%BD%93%E7%BB%84/2024

### What kind of hardware did the bug occur on?

Desktop

### On which operating system are you experiencing the problem?

Windows

### The version of your Operation System

windows10

### What browsers are you seeing the problem on?

Chrome

### The version of your Web browser

130.0.6723.92（

### What kind of network are you connecting to?

WiFi

### What network region are you in?

China mainland

### Anything else?

![image](https://github.com/user-attachments/assets/b57511bb-78e7-4fa3-8ca1-2d2c16d577ae)
https://kaiyuanshe.cn/department/%E5%AA%92%E4%BD%93%E7%BB%84/2024

**Comment by luojiyin1987** [comment]
@TechQuery

**Comment by dethan3** [comment]
目前这个页面的逻辑可能是所有未添加活跃状态的页面都是灰色处理，建议改变这种显示方式，改用添加标签之类的方式

**Comment by TechQuery** [comment]
> 目前这个页面的逻辑可能是所有未添加活跃状态的页面都是灰色处理

所有没填 OKR 或 4P 报告的组，当年视为冻结，就会变成灰色，并默认不在组织结构上显示。参见：https://applink.feishu.cn/client/message/link/open?token=AmGCjJI%2BywACZysU%2F36QwAM%3D

> 建议改变这种显示方式，改用添加标签之类的方式

考虑加标签，但觉得没那么明显。

同时一个真正死了的组通常当年也没有新人加入。如果那个组还有人，灰色头像就是一种巨大的刺激，让活组赶紧填报信息、死组赶紧复活。

**Comment by wangrunlin** [comment]
> > 目前这个页面的逻辑可能是所有未添加活跃状态的页面都是灰色处理
> 
> 所有没填 OKR 或 4P 报告的组，当年视为冻结，就会变成灰色，并默认不在组织结构上显示。参见：https://applink.feishu.cn/client/message/link/open?token=AmGCjJI%2BywACZysU%2F36QwAM%3D
> 
> > 建议改变这种显示方式，改用添加标签之类的方式
> 
> 考虑加标签，但觉得没那么明显。
> 
> 同时一个真正死了的组通常当年也没有新人加入。如果那个组还有人，灰色头像就是一种巨大的刺激，让活组赶紧填报信息、死组赶紧复活。

不活跃就是不活跃，去世了就是去世了。

一个组不活跃使整体页面置灰导致成员头像也都置灰的行为，在我看来是不够尊重成员曾经的贡献，并且在中国法律的文化下，头像变灰会引起一些不必要的联想（如去世）。

在一个正式的官网没必要做出这样玩梗的行为。

**Comment by luojiyin1987** [comment]
我只能说尊重你的选择

**Comment by TechQuery** [comment]
> 一个组不活跃使整体页面置灰导致成员头像也都置灰的行为，在我看来是不够尊重成员曾经的贡献

核心问题应该区分每年的活跃度，活跃的年份点进去应该是彩的，这一点确实需要优化。

> 并且在中国法律的文化下，头像变灰会引起一些不必要的联想（如去世）。

中国的法律从未规定头像是什么颜色代表怎样的生命状态，你只能说中国的文化是这么认为的。

> 在一个正式的官网没必要做出这样玩梗的行为。

我并没有在玩儿梗，我前面已经说了：这是我设计的激励措施。

**Comment by TechQuery** [comment]
> 我只能说尊重你的选择

这个功能上会讲过：https://kaiyuanshe.feishu.cn/wiki/OGWdwy6QTivhgQkeURec8zttnFc?from=from_parent_docs&subFrom=ordered&view=vewAIi1K9b#share-QqvrdI9bIo47M0xWZVScAsTYnmd

如果参会者当场没提出异议，事过很久后再说这个事情不合适，我觉得这本身就不太尊重功能开发者的时间和劳动。

**Comment by TechQuery** [comment]
> 印象里各个小组不都填写了OKR么？

我也有这个印象，在一个江波理事长的 Excel 表格中，但飞书搜不到……
