### ISSUE TITLE
顾问委员会和法律咨询委员会有重复人员

### ISSUE THREAD

**Issue by tk103331** [kaiyuanshe/kaiyuanshe.github.io#375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

重复的都是林旅强老师

https://kaiyuanshe.cn/department/committee/advisory
<img width="1299" alt="image" src="https://github.com/user-attachments/assets/b1e5ef0d-32bd-47c4-b86b-6a25aa806e8b" />

https://kaiyuanshe.cn/department/committee/legal-advisory
<img width="1102" alt="image" src="https://github.com/user-attachments/assets/974c687a-079c-415b-b49e-f972c3dbb050" />

### Expected Behavior

移除重复

### Steps To Reproduce

https://kaiyuanshe.cn/department/committee/advisory
https://kaiyuanshe.cn/department/committee/legal-advisory

### What kind of hardware did the bug occur on?

Desktop

### On which operating system are you experiencing the problem?

MacOS

### The version of your Operation System

14.1

### What browsers are you seeing the problem on?

Chrome

### The version of your Web browser

版本 131.0.6778.205（正式版本） (arm64)

### What kind of network are you connecting to?

WiFi

### What network region are you in?

China mainland

**Comment by TechQuery** [comment]
已解决：https://applink.feishu.cn/client/message/link/open?token=AmR8hd7hDQAcZ3GgOJsCwAI%3D
