### ISSUE TITLE
English Translation

### ISSUE THREAD

**Issue by niccokunzmann** [kaiyuanshe/kaiyuanshe.github.io#43]
Hello,

I just listened to the lightning talk about this conference at the FOSSASIA 2022 summit.
https://eventyay.com/e/6b901f56
I am interested in this conference but I can not speak Chinese yet. I am sorry. I wonder when the English translation will be available on the website. Is there anything we can do for that? I fear I might not be able to help though as I can not speak or read Chinese. I see the web page has a language button. This seems to only provide Chinese event when I click on English.

Kind regards,
Nicco Kunzmann

**Comment by cynbarby** [comment]
> Hello,
> 
> I just listened to the lightning talk about this conference at the FOSSASIA 2022 summit. https://eventyay.com/e/6b901f56 I am interested in this conference but I can not speak Chinese yet. I am sorry. I wonder when the English translation will be available on the website. Is there anything we can do for that? I fear I might not be able to help though as I can not speak or read Chinese. I see the web page has a language button. This seems to only provide Chinese event when I click on English.
> 
> Kind regards, Nicco Kunzmann

Hi Nicco, Do you really mean the FOSSASIA 2022 summit? All the lecturers at this conference are speaking English, I guess you might paste the wrong meeting link?

**Comment by robyle** [comment]
Google translate ok？

**Comment by TechQuery** [comment]
i18n has launched on New Test Web-site: https://test.kaiyuanshe.cn/
