### ISSUE TITLE
登陆注册 504

### ISSUE THREAD

**Issue by kylezhang** [kaiyuanshe/kaiyuanshe.github.io#45]
如题，在https://kaiyuanshe.vercel.app/user/sign-up 和 https://kaiyuanshe.vercel.app/user/sign-in 时，都出现了 504 下图的error。
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/3679798/179234773-bba9870b-15e9-4384-979b-174da1da718a.png">

**Comment by TechQuery** [comment]
感谢反馈！

后端测试服数据库实例过期了，最近准备放国内正式服，还没忙过来。
