### ISSUE TITLE
中国开源地图以 Landscape 的方式呈现

### ISSUE THREAD

**Issue by tedliu1** [kaiyuanshe/kaiyuanshe.github.io#61]
## 界面参考

参考 Linux 基金会或是 CNCF 的 Landscape 方式呈现：
https://landscape.linuxfoundation.org/
https://landscape.cncf.io/
https://landscape.lfai.foundation/

## 开源代码

https://github.com/cncf/lf-landscapes

**Comment by tedliu1** [comment]
LF Landscape 目前有 1,834 个条目（最后一条是浙江大学），这个 CSV 文档是可以直接下载的，里面许多信息是由 Crunchbase 以及 GitHub 里取得，对我们的中国开源地图来说很有参考价值。
[interactive-landscape.xlsx](https://github.com/kaiyuanshe/kaiyuanshe.github.io/files/9539613/interactive-landscape.xlsx)

**Comment by TechQuery** [comment]
感觉可以用这个图近似实现：
https://echarts.apache.org/examples/zh/editor.html?c=treemap-show-parent&lang=ts
