### ISSUE TITLE
重写开源许可证选择器

### ISSUE THREAD

**Issue by TechQuery** [kaiyuanshe/kaiyuanshe.github.io#69]
### 入口

https://kaiyuanshe.cn/license-tool/

### 代码

- 页面：https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/hexo/themes/Electron/layout/license-tool.ejs
- 逻辑：https://github.com/kaiyuanshe/kaiyuanshe.github.io/tree/hexo/themes%2FElectron%2Fsource%2FOSLS

**Comment by luojiyin1987** [comment]
@TechQuery   看了对应的页面和逻辑。 为什么要重写 ？ 重写的的方向？

**Comment by TechQuery** [comment]
> @TechQuery   看了对应的页面和逻辑。 为什么要重写 ？ 重写的的方向？  

因为老官网这种基于 Hexo 的老架构将被全面抛弃，就需要将基于老旧技术的模块用 React 这些组件化新技术重写。

**Comment by luojiyin1987** [comment]
`组件库是 React 封装过的 Bootstrap 5，以前用的是 Bootstrap 的老版本`
用的是这个  [Bootstap 5](https://github.com/idea2app/Next-Bootstrap-ts)   ?

**Comment by TechQuery** [comment]
> `组件库是 React 封装过的 Bootstrap 5，以前用的是 Bootstrap 的老版本` 用的是这个 [Bootstap 5](https://github.com/idea2app/Next-Bootstrap-ts) ?

你发的链接是上游脚手架，组件库是：
https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/4d2235233e6905c7eee73a010428905063e25503/package.json#L31

**Comment by luojiyin1987** [comment]
[项目地址](https://github.com/luojiyin1987/license-tool)

**Comment by luojiyin1987** [comment]
@TechQuery      尝试使用  Progress bars 组件，没成功，已经提交代码到main 分支。
[参考文档](https://react-bootstrap.netlify.app/components/progress/#rb-docs-content)

**Comment by TechQuery** [comment]
> @TechQuery      尝试使用  Progress bars 组件，没成功，已经提交代码到main 分支。
> 
> [项目地址](https://github.com/luojiyin1987/license-tool)
> [参考文档](https://react-bootstrap.netlify.app/components/progress/#rb-docs-content)   

具体是什么问题？

**Comment by luojiyin1987** [comment]
这是文档里 
![image](https://user-images.githubusercontent.com/6524977/198870778-d2c1f93b-4049-41e5-9788-f5d2ded4f976.png)


这是自己的页面
![image](https://user-images.githubusercontent.com/6524977/198870848-e868d749-34cd-41b9-b680-68f622ad7832.png)

**Comment by TechQuery** [comment]
> @TechQuery 尝试使用 Progress bars 组件，没成功，已经提交代码到main 分支。
> 
> [项目地址](https://github.com/luojiyin1987/license-tool) [参考文档](https://react-bootstrap.netlify.app/components/progress/#rb-docs-content)

没有引入 CSS 库

https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/4d2235233e6905c7eee73a010428905063e25503/pages/_document.tsx#L20-L23

**Comment by luojiyin1987** [comment]
https://github.com/luojiyin1987/license-tool/blob/f9ad4f1df497cc4e05efbc88b384ed019ddad754/pages/index.tsx#L2-L6


可以了

**Comment by luojiyin1987** [comment]
@TechQuery  明白了， 要有返回值。  我的写法要加 `return` , 你的写法是 `( )` 是直接返回表单式的值.

**Comment by luojiyin1987** [comment]
@TechQuery 
 1. https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/b7d2c4acccb609704c5a12eba0bd4f0d87c8dec5/themes/Electron/source/OSLS/licencedifferentiator.js#L348-L358
是不是在 文件`licencedifferentiator.js` 只要关注这段代码？

2.
在文件 `licens-tool.js`  中 使用了  `licencedifferentiator.js` 中的  `processChoice` 函数？ 
https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/b7d2c4acccb609704c5a12eba0bd4f0d87c8dec5/themes/Electron/source/OSLS/license-tool.js#L109-L112

**Comment by luojiyin1987** [comment]
https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/b7d2c4acccb609704c5a12eba0bd4f0d87c8dec5/themes/Electron/source/OSLS/licencedifferentiator.js#L53-L64
我不太明白 这段函数的作用， 防止重复计算评分 `score`？

**Comment by TechQuery** [comment]
这些是国外开源项目很早的代码，我也没细看。你根据功能效果来重写即可，只有基础数据是可以照搬的。

**Comment by luojiyin1987** [comment]
https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/b7d2c4acccb609704c5a12eba0bd4f0d87c8dec5/themes/Electron/source/OSLS/licencedifferentiator.js#L176-L179
 评分是根据 当前选择 跟协议的要求 匹配个数决定的？

**Comment by TechQuery** [comment]
具体规则我也没研究，可以在飞书群里讨论。

你就把旧版当**可交互原型**，从零手写一遍就行。

**Comment by luojiyin1987** [comment]
https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/b7d2c4acccb609704c5a12eba0bd4f0d87c8dec5/themes/Electron/source/OSLS/licencedifferentiator.js#L178 

https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/b7d2c4acccb609704c5a12eba0bd4f0d87c8dec5/themes/Electron/source/OSLS/licencedifferentiator.js#L282
@TechQuery    为什么有两种分数的统计逻辑？ 

我将统一用 100 分进行计算

**Comment by TechQuery** [comment]
> https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/b7d2c4acccb609704c5a12eba0bd4f0d87c8dec5/themes/Electron/source/OSLS/licencedifferentiator.js#L178
> 
> https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/b7d2c4acccb609704c5a12eba0bd4f0d87c8dec5/themes/Electron/source/OSLS/licencedifferentiator.js#L282
> 
> 
> @TechQuery 为什么有两种分数的统计逻辑？
> 我将统一用 100 分进行计算

不用管，十分制都可以。

做完算法库再写界面：https://github.com/kaiyuanshe/Open-Source-License-filter
