### ISSUE TITLE
议题详情页

### ISSUE THREAD

**Issue by TechQuery** [kaiyuanshe/kaiyuanshe.github.io#91]
## 竞品

https://coscup.org/2019/programs/b6545d0f-42de-4b72-83c0-35bf8fba92be

### 任务

- kaiyuanshe/PWA#5
- kaiyuanshe/COSCon-2020-Apache-Roadshow---China#8

### 代码

https://github.com/kaiyuanshe/PWA/blob/master/src/page/Activity/AgendaDetail.tsx

**Comment by PapayaHUANG** [comment]
@PapayaHUANG 图片尺寸调整

**Comment by PapayaHUANG** [comment]
> @PapayaHUANG 图片尺寸调整

图片裁剪已完成
