### ISSUE TITLE
邀请函生成器

### ISSUE THREAD

**Issue by TechQuery** [kaiyuanshe/kaiyuanshe.github.io#92]
## 功能

直接根据飞书多维表格的基础数据自动生成，无需手动操作。

### Web Conf 成都

https://github.com/FreeCodeCamp-Chengdu/Web-Conf/blob/master/source/page/2019/InvitationCard.tsx

### COSCon 旧版

https://github.com/kaiyuanshe/coscon-poster

**Comment by luojiyin1987** [comment]
1  是否再运行一个nodejs 后端， 避免出现开发的相关key  ？
2  是不是从飞书打开该网站？ 
3 是不是获取飞书相关的账号信息作为报名信息？  像 论坛信息   成员信息 演讲信息设置一个默认值？ 
@TechQuery

**Comment by luojiyin1987** [comment]
遇到个小问题，对nodejs 的版本有要求，
https://github.com/Ovilia/acasia-poster/issues/3

**Comment by TechQuery** [comment]
> ~~1  是否再运行一个nodejs 后端， 避免出现开发的相关key  ？~~
> 2  是不是从飞书打开该网站？ 
> 3 是不是获取飞书相关的账号信息作为报名信息？  像 论坛信息   成员信息 演讲信息设置一个默认值？ 
> @TechQuery      

2 不是，是在官网议题详情页上面点开讲师邀请函。

3 论坛、演讲、讲师信息都在那个飞书多维表格里，直接接口读取，不需要任何人手工填写。

**Comment by luojiyin1987** [comment]
https://github.com/kaiyuanshe/coscon-poster 
 我应该在这个项目上进行开发？  
@TechQuery

**Comment by luojiyin1987** [comment]
> 2 不是，是在官网议题详情页上面点开讲师邀请函。

我没找到入口的地方

**Comment by TechQuery** [comment]
> 
> > 2 不是，是在官网议题详情页上面点开讲师邀请函。
> 
> 我没找到入口的地方

设计上是从 #91 这里进，但你可以先从大会主页的议题卡片点进去，因为两者都需要拿议题和讲师的数据：

https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/07375ad047427f96ccd314fb7f35ddba09cd7927/components/Activity/Agenda/Card.tsx#L28

**Comment by luojiyin1987** [comment]
> 设计上是从 #91 这里进，但你可以先从大会主页的议题卡片点进去，因为两者都需要拿议题和讲师的数据：

https://kaiyuanshe.cn/activity  这个入口？

**Comment by TechQuery** [comment]
>  > 设计上是从 #91 这里进，但你可以先从大会主页的议题卡片点进去，因为两者都需要拿议题和讲师的数据：
> 
> https://kaiyuanshe.cn/activity  这个入口？
> 

是某个活动的议题列表：https://kaiyuanshe.cn/activity/recNgZ1MiV
